FROM node:slim AS build

WORKDIR /opt/app

RUN npm install -g pkg@4.3.4

COPY package.json /opt/app/package.json
RUN npm install

COPY app.js /opt/app/app.js

RUN pkg -t node8-alpine-x64 --public app.js -o /opt/app/build

FROM alpine

RUN apk add --no-cache libstdc++

COPY --from=build /opt/app/build /opt/app

ENTRYPOINT ["/opt/app"]